In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("D:/Churn_Modelling.csv")
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
dataset.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [6]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
X = dataset.loc[:, ['CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary']]
y = dataset.loc[:, ['Exited']]

In [8]:
states=pd.get_dummies(X['Geography'],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [9]:
X=pd.concat([X,states,gender],axis=1)

In [10]:
X=X.drop(['Geography','Gender'],axis=1)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [14]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))

# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))

# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 6s 4ms/step - loss: 0.5797 - accuracy: 0.7911
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4237 - accuracy: 0.7996
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3798 - accuracy: 0.8365
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3653 - accuracy: 0.8467
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3419 - accuracy: 0.8623
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3429 - accuracy: 0.8620
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3474 - accuracy: 0.8617
Epoch 8/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3458 - accuracy: 0.8573
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3528 - accuracy: 0.8583
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3252 - accuracy: 0.8677
Epoch 11/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3439 - accuracy: 0.8622
Epoch 12/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3441 - accuracy: 0.8582
Epoch 13/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3482 - accuracy: 0.8574: 0s - loss: 0.3496
Epoch 14/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3354 - accuracy: 0.8619
Epoch 15/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8587
Epoch 16/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3365 - accuracy: 0.8646
Epoch 17/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.8633
Epoch 18/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3432 - accuracy: 0.8646
Epoch 19/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3408 - accuracy: 0.8630
Epoch 20/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3331 - accuracy: 0.8633
Epoch 21/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3299 - accuracy: 0.8656
Epoch 22/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3290 - accuracy: 0.8687
Epoch 23/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3324 - accuracy: 0.8639
Epoch 24/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3308 - accuracy: 0.8654
Epoch 25/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3351 - accuracy: 0.8615
Epoch 26/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3488 - accuracy: 0.8570
Epoch 27/100
800/800 [==============================] - ETA: 0s - loss: 0.3226 - accuracy: 0.86 - 3s 3ms/step - loss: 0.3229 - accuracy: 0.8686
Epoch 28/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3345 - accuracy: 0.8662
Epoch 29/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3362 - accuracy: 0.8681
Epoch 30/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3377 - accuracy: 0.8604
Epoch 31/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3314 - accuracy: 0.8650
Epoch 32/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3244 - accuracy: 0.8708
Epoch 33/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3295 - accuracy: 0.8670
Epoch 34/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3296 - accuracy: 0.8661
Epoch 35/100
800/800 [==============================] - ETA: 0s - loss: 0.3328 - accuracy: 0.86 - 3s 4ms/step - loss: 0.3328 - accuracy: 0.8640
Epoch 36/100
800/800 [==============================] - 3s 4ms/step - loss: 0.3374 - accuracy: 0.8571: 1s - loss: 0.3388 - accuracy: 0. - ETA: 1s - loss:
Epoch 37/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3380 - accuracy: 0.8626
Epoch 38/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3465 - accuracy: 0.8575
Epoch 39/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3283 - accuracy: 0.8649
Epoch 40/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3246 - accuracy: 0.8714
Epoch 41/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3304 - accuracy: 0.8629
Epoch 42/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3266 - accuracy: 0.8665
Epoch 43/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3309 - accuracy: 0.8606
Epoch 44/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3339 - accuracy: 0.8654
Epoch 45/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3426 - accuracy: 0.8577
Epoch 46/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3339 - accuracy: 0.8582
Epoch 47/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3339 - accuracy: 0.8668
Epoch 48/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3266 - accuracy: 0.8659
Epoch 49/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3361 - accuracy: 0.8628
Epoch 50/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3268 - accuracy: 0.8699
Epoch 51/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3293 - accuracy: 0.8653
Epoch 52/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3409 - accuracy: 0.8585
Epoch 53/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3212 - accuracy: 0.8714
Epoch 54/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8593
Epoch 55/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3323 - accuracy: 0.8647
Epoch 56/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3316 - accuracy: 0.8651
Epoch 57/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3271 - accuracy: 0.8664
Epoch 58/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3462 - accuracy: 0.8541
Epoch 59/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3383 - accuracy: 0.8648
Epoch 60/100
800/800 [==============================] - 3s 4ms/step - loss: 0.3349 - accuracy: 0.8648
Epoch 61/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3393 - accuracy: 0.8603
Epoch 62/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3290 - accuracy: 0.8633
Epoch 63/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3337 - accuracy: 0.8617
Epoch 64/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3333 - accuracy: 0.8676
Epoch 65/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3417 - accuracy: 0.8588
Epoch 66/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3325 - accuracy: 0.8613
Epoch 67/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3271 - accuracy: 0.8671
Epoch 68/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3357 - accuracy: 0.8636
Epoch 69/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3317 - accuracy: 0.8602: 0s - los
Epoch 70/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3366 - accuracy: 0.8645
Epoch 71/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3432 - accuracy: 0.8603
Epoch 72/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3310 - accuracy: 0.8627
Epoch 73/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3411 - accuracy: 0.8597
Epoch 74/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3307 - accuracy: 0.8635
Epoch 75/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3481 - accuracy: 0.8586
Epoch 76/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3462 - accuracy: 0.8552
Epoch 77/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3375 - accuracy: 0.8632
Epoch 78/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3377 - accuracy: 0.8596
Epoch 79/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3271 - accuracy: 0.8687
Epoch 80/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3431 - accuracy: 0.8605
Epoch 81/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3289 - accuracy: 0.8665
Epoch 82/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3333 - accuracy: 0.8637
Epoch 83/100
800/800 [==============================] - 3s 4ms/step - loss: 0.3330 - accuracy: 0.8659
Epoch 84/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3294 - accuracy: 0.8646
Epoch 85/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3429 - accuracy: 0.8604
Epoch 86/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3323 - accuracy: 0.8611
Epoch 87/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3421 - accuracy: 0.8610
Epoch 88/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3386 - accuracy: 0.8643
Epoch 89/100
800/800 [==============================] - 2s 3ms/step - loss: 0.3326 - accuracy: 0.8658: 0s - loss: - ETA: 0s - loss: 0.3319
Epoch 90/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3283 - accuracy: 0.8648
Epoch 91/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3404 - accuracy: 0.8594
Epoch 92/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3329 - accuracy: 0.8611
Epoch 93/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3303 - accuracy: 0.8641
Epoch 94/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3425 - accuracy: 0.8598
Epoch 95/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3303 - accuracy: 0.8676
Epoch 96/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3329 - accuracy: 0.8640
Epoch 97/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3309 - accuracy: 0.8635
Epoch 98/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3331 - accuracy: 0.8649
Epoch 99/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3291 - accuracy: 0.8639
Epoch 100/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3229 - accuracy: 0.8704

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred, y_test)

array([[1524,  199],
       [  71,  206]], dtype=int64)

In [25]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("True Negatives: ",tn)
print("False Positives: ",fp)
print("False Negatives: ",fn)
print("True Positives: ",tp)

True Negatives:  1524
False Positives:  71
False Negatives:  199
True Positives:  206

In [24]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.865